---
title: "R03_6_POST_ibon"
author: "Jilung Hsieh"
date: "9/22/2019"
output:
  html_document:
    highlight: zenburn
    number_sections: yes
    theme: cerulean
    toc: yes
    css: style.css
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Crawler design
1. Finding way to get the first page of data
2. Finding way to get back all page



```{r}
library(tidyverse)
library(httr) # GET(), POST(), content()
library(rvest) # read_html(), html_nodes(), html_text()
options(stringsAsFactors = F)
```


# Getting county

## No pipeline

```{r}
# The url
url <- "http://www.ibon.com.tw/retail_inquiry.aspx#gsc.tab=0"
browseURL(url)

```

## Pipeline
```{r}

# Writing as pipeline version
url <- "http://www.ibon.com.tw/retail_inquiry.aspx#gsc.tab=0"

```

# POST: Getting address of Taipei city
- Is it possible to use `GET()` to get back Taipei city's ibon address?

## Getting back html with `POST()`
```{r}
# Finding the url



# Using POST to send parameters



# httr::content() to convert response to textual data


# cat() to save textual data to html file


# browseURL() to re-open the html in your browser


```

## Retrieveing data in nodes
```{r}
# Converting response to text by content() and parsing to xml_document by read_html(), assign to var 'doc'


# Selecting nodes


# Retrieving text from nodes


# Using html_table() function



```



# Getting and binding all counties' data

```{r}




```


# Cleaning data

# Retrieving town names 
```{r}


```

